name: Android CI

on:
  push:
    branches: [ master ]
    tags:
      - zee*/vc*/vn*
      - dcbuildzee*/vc*/vn*
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Get Tag
      run: echo "fullTagValue=${{github.ref_name}}" >> $GITHUB_ENV
    - name: Print Tag
      run: echo ${{env.fullTagValue}}
    - name: Is RC Build
      run: |
        echo "actualTagValue=${{env.fullTagValue}} | sed 's/dcbuild//g'" >> $GITHUB_ENV
        if [[ ${{env.fullTagValue}} =~ "dcbuild" ]]; then
          echo "isRCBuild=0" >> $GITHUB_ENV
        else 
          echo "isRCBuild=1" >> $GITHUB_ENV
        fi
    - name: Print RC Build
      run: |
        echo ${{env.isRCBuild}}
        echo ${{env.actualTagValue}}
        
        set -e

        DIGIT=[0-9]
        if [[ "${{ env.actualTagValue }}" =~ zee($DIGIT+)/vc($DIGIT{9})/vn($DIGIT{2})\.($DIGIT{1}) ]]; then
          echo "if"
          echo "${BASH_REMATCH[0]}" # full (matched) string, e.g. zee34/vc203230230/vn11.9
          echo "${BASH_REMATCH[1]}" # Major/Fix Version
          echo "${BASH_REMATCH[2]}" # versionCode
          echo "${BASH_REMATCH[3]}" # Group Number
          echo "${BASH_REMATCH[4]}" # Respin Count
          
          echo "VERSION_CODE=${BASH_REMATCH[2]}" >> $GITHUB_ENV
          echo "VERSION_NAME=${BASH_REMATCH[1]}.1${{{env.VERSION_CODE}}:6}${BASH_REMATCH[3]}${BASH_REMATCH[4]}" >> $GITHUB_ENV
        else
          echo "else"
        fi
    - name: Print App Version
      run: |
        echo ${{env.VERSION_CODE}}
        echo ${{env.VERSION_NAME}}
