name: Android CI

on:
  push:
    branches: [ master ]
    tags:
      - zee*/vc*/vn*
      - dcbuild/zee*/vc*/vn*
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Get Tag
      run: echo "actualTagValue=${{github.ref_name}}" >> $GITHUB_ENV
    - name: Print Tag
      run: echo ${{env.actualTagValue}}
    - name: Is RC Build
      run: |
        if [[ ${{env.actualTagValue}} =~ "dcbuild" ]]; then
          echo "isRCBuild=0" >> $GITHUB_ENV
        else 
          echo "isRCBuild=1" >> $GITHUB_ENV
        fi
    - name: Print DC Build
      run: echo ${{env.isRCBuild}}
